🐛 Fix KeyError in mod_status command
Fixed:
- Changed stats['warnings'] to stats.get('warns', 0)
- Changed to use .get() method with default value of 0
- Matches the keys returned by get_moderation_stats() method (warns, timeouts, kicks, bans)

Error resolved:
KeyError: 'warnings' in mod_status command at line 446